#!/usr/bin/env ruby

require_relative './fst-test-framework'

FST.test('crk-descriptive-analyzer') do
  #transduce "nipa", contains: "nipâw+V+AI+Imp+Imm+2Sg"
  transduce "nipâ", contains: "nipâw+V+AI+Imp+Imm+2Sg"
end
