#!/usr/bin/env ruby

require_relative './fst-test-framework'

FST.test('crk-strict-analyzer') do
  transduce "nipâ", contains: "nipâw+V+AI+Imp+Imm+2Sg"
  transduce "nipâw", contains: "nipâw+V+AI+Ind+Prs+3Sg"
end

FST.test('crk-descriptive-analyzer') do
  transduce "nipa", contains: "nipâw+V+AI+Imp+Imm+2Sg"
  transduce "nipâ", contains: "nipâw+V+AI+Imp+Imm+2Sg"
  transduce "n'paw", contains: "nipâw+V+AI+Ind+Prs+3Sg"
  transduce "nin'pan", contains: "nipâw+V+AI+Ind+Prs+1Sg"
  transduce "neeyu", contains: "niya+Pron+Pers+1Sg"

  # https://github.com/UAlbertaALTLab/plains-cree-fsts/issues/20
  transduce "nepat", contains: "IC+nipâw+V+AI+Cnj+Prs+3Sg"
  transduce "nipayan", contains: "pê-ayâw+V+AI+Ind+Prs+1Sg"
  transduce "nipayan", contains: "nipâw+V+AI+Cnj+Prs+2Sg"
  transduce "nipayan", contains: "nipâw+V+AI+Cnj+Prs+1Sg"
  transduce "meyonipat", contains: "IC+PV/miyo+nipâw+V+AI+Cnj+Prs+3Sg"

  # https://github.com/UAlbertaALTLab/cree-intelligent-dictionary/issues/370
  transduce "yahyanam", contains: "yâhyânam+V+AI+Ind+Prs+3Sg"
  transduce "niyahyanen", contains: "yâhyânam+V+AI+Ind+Prs+1Sg"
end

FST.test('crk-normative-generator') do
  # https://github.com/UAlbertaALTLab/plains-cree-fsts/issues/20
  transduce "pê-ayâw+V+AI+Ind+Prs+1Sg", contains: "nipê-ayân"
  transduce "IC+PV/miyo+nipâw+V+AI+Cnj+Prs+3Sg", contains: "mêyo-nipât"
end

