# Autogenerated file. DO NOT MODIFY!
LICENCE:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/LICENCE -o $@
AUTHORS:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/AUTHORS -o $@
src/morphological-fst-rules.mk:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/morphological-fst-rules.mk -o $@
src/morphology/root.lexc:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/morphology/root.lexc -o $@
src/morphology/affixes/noun_affixes.lexc:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/morphology/affixes/noun_affixes.lexc -o $@
src/morphology/affixes/verb_affixes.lexc:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/morphology/affixes/verb_affixes.lexc -o $@
src/morphology/stems/derivation_stems.lexc:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/morphology/stems/derivation_stems.lexc -o $@
src/morphology/stems/non_standard.lexc:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/morphology/stems/non_standard.lexc -o $@
src/morphology/stems/noun_stems.lexc:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/morphology/stems/noun_stems.lexc -o $@
src/morphology/stems/noun_vocatives.lexc:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/morphology/stems/noun_vocatives.lexc -o $@
src/morphology/stems/numerals.lexc:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/morphology/stems/numerals.lexc -o $@
src/morphology/stems/particles.lexc:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/morphology/stems/particles.lexc -o $@
src/morphology/stems/pronouns.lexc:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/morphology/stems/pronouns.lexc -o $@
src/morphology/stems/verb_stems.lexc:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/morphology/stems/verb_stems.lexc -o $@
src/phonology/crk-phon.twolc:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/phonology/crk-phon.twolc -o $@
src/phonology/crk-phon-morph-bound.twolc:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/phonology/crk-phon-morph-bound.twolc -o $@
src/orthography/spellrelax.regex:
	mkdir -p $(dir $@)
	$(CURL) $(HTTP_PREFIX)/src/orthography/spellrelax.regex -o $@
